/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.0.0/userguide/building_java_projects.html in the Gradle documentation.
 */
plugins {
    java
   id("org.springframework.boot") version "3.1.0"
   id("io.spring.dependency-management") version "1.1.0"
   application
}


java {
   toolchain {
       languageVersion.set(JavaLanguageVersion.of(21))
   }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.apache.commons:commons-text:1.10.0")
    implementation(project(":instructional-lib"))
    implementation("org.springframework.boot:spring-boot-starter")
    testImplementation("org.springframework.boot:spring-boot-starter-test")

}



application {
   // Define the main class for the application.
   mainClass.set("org.example.Lesson2")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}